name: incremental_dom
version: 0.1.0-pre2
author: Justin Fagnani <justinfagnani@google.com>
description: A Dart incremental DOM library.
homepage: https://github.com/justinfagnani/incremental-dom.dart
dependencies:
  reflectable: ">=0.1.2 <0.2.0"
dev_dependencies:
  test: any
